const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};
const quiz = {
  quizTitle: 'React Quiz Component Demo',
  quizSynopsis: 'Test your knowledge of React components with this quick 6-question quiz. Dive into the core concepts of React, including state, props, lifecycle methods, and more!',
  nrOfQuestions: '6',
  progressBarColor: '#9de1f6',
  questions: [
    {
      question: 'How can you access the state of a component from inside of a member function?',
      questionPic: 'https://dummyimage.com/600x400/000/fff&text=X',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'this.getState()',
        'this.prototype.stateValue',
        'this.state',
        'this.values',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: 'The correct way to access a component’s state in React is using `this.state`. `this.getState()` and `this.values` are incorrect, and `this.prototype.stateValue` refers to an object prototype, which is not relevant to React state management.',
      point: '20',
      segment: segment.advanced,
    },
    {
      question: 'ReactJS is developed by ?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Google Engineers',
        'Facebook Engineers',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: 'ReactJS was developed by Facebook Engineers, particularly by Jordan Walke in 2011. Google is not associated with the development of React.',
      point: '20',
      segment: segment.basic,
    },
    {
      question: 'ReactJS is an MVC based framework?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: 'ReactJS is not an MVC-based framework; it is a library primarily concerned with building user interfaces. While React can work within MVC frameworks, it focuses on the "View" part of MVC.',
      point: '10',
    },
    {
      question: 'Which of the following concepts is/are key to ReactJS?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Component-oriented design',
        'Event delegation model',
        'Both of the above',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: 'Both component-oriented design and the event delegation model are key concepts in ReactJS. Component-oriented design allows reusable UI building blocks, and event delegation improves performance by managing event handlers at a higher level.',
      point: '30',
      segment: segment.medium,
    },
    {
      question: 'How does the initial page of any react project looks like if we create the project using vite',
      questionType: 'photo',
      answerSelectionType: 'single',
      answers: [
        'https://github.com/wingkwong/react-quiz-component/assets/35857179/e169cd44-13a7-4301-9d30-6c0859d3ac35',
        'https://github.com/wingkwong/react-quiz-component/assets/35857179/30b4aa3d-2523-4d73-9e3b-27ce44ffd50a',
        'https://github.com/wingkwong/react-quiz-component/assets/35857179/64da0348-30b7-4a13-9fea-791537c49109',
        'https://github.com/wingkwong/react-quiz-component/assets/35857179/660e9255-8a16-4e0f-a7e4-81ba6ac0f9bc',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: 'When you create a React project using Vite, the initial page has a minimalist design that showcases a Vite logo and some boilerplate code instructions. The first image shows the default Vite project startup page.',
      point: '20',
    },
    {
      question: 'What are the advantages of React JS?',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'React can be used on client and as well as server side too',
        'Using React increases readability and makes maintainability easier. Component, Data patterns improves readability and thus makes it easier for manitaining larger apps',
        'React components have lifecycle events that fall into State/Property Updates',
        'React can be used with any other framework (Backbone.js, Angular.js) as it is only a view layer',
      ],
      correctAnswer: [1, 2, 4],
      messageForCorrectAnswer: 'Correct answer. Good job.',
      messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      explanation: 'The key advantages of React include its ability to be used on both the client and server side, improved readability and maintainability through its component-based structure, and its flexibility to be used with other frameworks since it focuses solely on the view layer.',
      point: '20',
    },
  ],
};

export default quiz;
